### ISSUE TITLE
Android 4.4.2 exception

### ISSUE THREAD

**Issue by amccorma** [chrisriesgo/xamarin-forms-carouselview#5]
pagerIndicator.SetBinding(PagerIndicatorTabs.ColumnDefinitionsProperty, "Pages", BindingMode.Default, new SpacingConverter());

If you get passed the exception below, you get an exception in the renderer.
            var a = new ViewPager(this.Context);
            var b = a.ClipBounds;

  --- End of managed exception stack trace ---
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    ... 2 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.ArgumentException: Value was an invalid value for ColumnDefinitions
Parameter name: value
at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty,object,Xamarin.Forms.BindableObject/SetValueFlags,Xamarin.Forms.BindableObject/SetValuePrivateFlags) <IL 0x000bb, 0x0039f>
at Xamarin.Forms.BindingExpression.ApplyCore (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,bool) <IL 0x00213, 0x00ab7>
at Xamarin.Forms.BindingExpression.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty) <IL 0x0007a, 0x002bf>
at Xamarin.Forms.Binding.Apply (object,Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty) <IL 0x0004b, 0x001ab>
at Xamarin.Forms.BindableObject.SetBinding (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindingBase,bool) <IL 0x000b1, 0x002eb>
at Xamarin.Forms.BindableObject.SetBinding (Xamarin.Forms.BindableProperty,Xamarin.Forms.BindingBase) <IL 0x00004, 0x0003f>
at Xamarin.Forms.BindableObjectExtensions.SetBinding (Xamarin.Forms.BindableObject,Xamarin.Forms.BindableProperty,string,Xamarin.Forms.BindingMode,Xamarin.Forms.IValueConverter,string) <IL 0x0002d, 0x00153>
at CustomLayouts.HomePage.CreateTabs () [0x0004c] in /Users/mccorma/Desktop/xamarin-forms-carouselview-master/src/CustomLayouts/HomePage.cs:127
at CustomLayouts.HomePage..ctor (CustomLayouts.Controls.CarouselLayout/IndicatorStyleEnum) [0x0006f] in /Users/mccorma/Desktop/xamarin-forms-carouselview-master/src/CustomLayouts/HomePage.cs:38
at CustomLayouts.SwitcherPage.<SwitcherPage>m__1 (object) [0x00007] in /Users/mccorma/Desktop/xamarin-forms-carouselview-master/src/CustomLayouts/SwitcherPage.cs:21
at Xamarin.Forms.Command.Execute (object) <IL 0x00007, 0x0002f>
at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () <IL 0x00011, 0x0007c>
at Xamarin.Forms.Platform.Android.ButtonRenderer/ButtonClickListener.OnClick (Android.Views.View) <IL 0x00015, 0x0009b>
at Android.Views.View/IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/1879/5f55a9ef/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.View.cs:1888
at (wrapper dynamic-method) object.69b6d15e-6d08-45c8-a840-5ee6f869e334 (intptr,intptr,intptr) <IL 0x00017, 0x00027>

```
at md5530bd51e982e6e7b340b73e88efe666e.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
at md5530bd51e982e6e7b340b73e88efe666e.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:29)
at android.view.View.performClick(View.java:4438)
at android.view.View$PerformClick.run(View.java:18422)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
... 5 more
```

**Comment by chrisriesgo** [comment]
@amccorma - I'm having trouble replicating this issue. Do you have any additional steps that you can provide? 
- Did you change any code?
- Are you testing on an emulator or real device?
- Are your Android SDKs + build tools up to date?

**Comment by e862** [comment]
Hi chrisriesgo,
I do have the same issue. The only thing I did to the original code was:
    Install-Package Xamarin.Forms -Version 1.5.0.6447
It fails here: HomePage.cs, View CreateTabs(), pagerIndicator.SetBinding(PagerIndicatorTabs.ColumnDefinitionsProperty, "Pages", BindingMode.Default, new SpacingConverter());

I then fell back to 
    Install-Package Xamarin.Forms -Version 1.4.4.6449
with the same issue.

Only going back to the original version of Xamarin Forms
    Install-Package Xamarin.Forms -Version 1.4.2.6359
worked.

Device: Samsung Galaxy S6, Factory reset, nothing installed
SDK: Android SDK 5.1.1 (API22)

Thanks, crisriesgo for looking into this. Maybe my findings help to point in the right direction.
 And thanks for the code! :) e862

**Comment by amccorma** [comment]
It has been a long time since I looked at it.  I reviewed my solution that fixed the issue. I did a workaround and forgot to post it.  

_In PagerIndicatorTabs.cs, change ItemsSourceChanged to:_

> void ItemsSourceChanged ()
> {
>  if (ItemsSource == null) return;
> 
> this.ColumnDefinitions.Clear ();
> foreach(var item in ItemsSource)
> {
> this.ColumnDefinitions.Add(new ColumnDefinition() { Width = new GridLength(1, GridUnitType.Star) });
>      }
>      CreateTabs();
> }

_In HomePage.cs change:_

remove the binding for ColumnDefintions.

> Xamarin.Forms.View CreateTabs()
>       {
>           var pagerIndicator = new PagerIndicatorTabs() { HorizontalOptions = LayoutOptions.CenterAndExpand };
>           pagerIndicator.RowDefinitions.Add(new RowDefinition() { Height = 50 });
>           pagerIndicator.SetBinding (PagerIndicatorTabs.ItemsSourceProperty, "Pages");
>           pagerIndicator.SetBinding (PagerIndicatorTabs.SelectedItemProperty, >"CurrentPage");
>           return pagerIndicator;
>       }

**Comment by amccorma** [comment]
The issue is the ColumnDefinitionsProperty binding is not working on the S6.

**Comment by e862** [comment]
Hi amccorma, and many thanks for quick response!
It works and it saved me quite some time. Greetings, e862

**Comment by Zilounay** [comment]
This solution works but the dots/tabs now _don't update anymore when swiping_. I tested on iOS.

**Comment by ionixjunior** [comment]
Thank you @amccorma your workaround works perfectly. Tested on Android API 22, iOS 8.4 and 9.2.

@Zilounay you need a help for solve this?

**Comment by amccorma** [comment]
Zilounay:  the issue with the dots is the event handler (command is not attached to the button)

In PagerIndicatorTabs.cs find CreateTabs method.  at the button create code attach the command:

```
            var tgr = new TapGestureRecognizer();
            tgr.Command = new Command(() =>
            {
                SelectedItem = ItemsSource[index];
            });
            tab.GestureRecognizers.Add(tgr);
            Children.Add(tab, index, 0);
```

**Comment by chrisriesgo** [comment]
Made some changes based on @amccorma's findings. Closing the issue.
